import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
const inter = Inter({ subsets: ["latin"] });
import TopBar from "@/components/TopBar";
import { ContentLeft, ContentCenter, ContentRight } from "@/components/Content";

export default function Home() {
  return (
    <>
      <Head>
        <title>Rexhent App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.inter} ${styles.content} fo`}>
        <TopBar />
        <div className={styles.mainContainer}>
          {/* <ContentLeft /> */}
          <ContentCenter />
          {/* <ContentRight /> */}
        </div>
        <footer className={styles.footer}>
          <p>Copyright &copy; rexhent {new Date().getFullYear()}.</p>
        </footer>
      </main>
    </>
  );
}
